### ISSUE TITLE
Missing data.py and Hardcoded request_*.jsonl Files

### ISSUE THREAD

**Issue by lappemic** [tiny-rawr/ZH_008_parallel_chatgpt_processing#1]
**Issue Description**

While exploring the repository, I noticed that the project appears to be missing critical components, specifically the data.py file and the hardcoded request_*.jsonl files.

**Expected Behavior**

The repository should contain all necessary files for it to function correctly. The data.py file is expected to be present as it is integral to the project's functionality. Additionally, request_*.jsonl files, which I assume contain the data for the API calls, are also expected to be part of the repository.

**Current Behavior**

Currently, cloning and setting up the repository results in errors due to the absence of data.py and request_*.jsonl files.

**Steps to Reproduce**

Clone the repository.
Follow the setup instructions in the README.
Notice the absence of data.py and errors related to missing request_*.jsonl files.

**Possible Solution**

If these files are meant to be part of the repository, please add data.py and the appropriate request_*.jsonl files. If they are generated or should be created by the users, consider updating the documentation to include instructions on how to create or generate these files.

**Additional Context**

The lack of these files prevents users from successfully running and utilizing the project. Providing these files or clear instructions on how to create them would be greatly appreciated by all users looking to leverage this repository for parallel processing with ChatGPT.

**Comment by XAVIXXVI** [comment]
@lappemic 

**Solution**

Modify the prompt as required in the generate_requests.py file and uncomment the below line in main.py 
`generate_chat_completion_requests(requests_filepath, data, prompt, model_name="gpt-3.5-turbo-16k")`
Add your input.csv file and run the main.py file it will automatically create the data.py and the other two .jsonl files.
You may get an error it says we can ignore it so just ignore it.

@tiny-rawr 
Thank you for your work and please modify your README.md instruction for more clarity.

Thank you [https://github.com/JLTube] for finding the solution.

**Comment by XAVIXXVI** [comment]
@lappemic please close this issue, thank you!
